name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
    steps:
      - id: get-user
        run: echo "uid_gid=$(id -u):$(id -g)" >> $GITHUB_OUTPUT

  build_application:
    name: Build application using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@v1
    with:
      upload_app_binaries_artifact: "compiled_app_binaries"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install deps
        run: |
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
          make deps
      - run: make cpp_test

  build_ledger:
    needs: configure
    runs-on: ubuntu-latest
    container:
      image: zondax/ledger-app-builder:latest
      options: --user ${{ needs.configure.outputs.uid_gid }}
      env:
        BOLOS_SDK: /opt/nanos-secure-sdk
    outputs:
      size: ${{steps.build.outputs.size}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build Standard app
        id: build
        shell: bash -l {0}
        run: |
          make
          echo "size=$(python3 deps/ledger-zxlib/scripts/getSize.py s)" >> $GITHUB_OUTPUT

  test_zemu:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          id
          echo $HOME
          echo $DISPLAY
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - run: sudo apt-get update -y && sudo apt-get install -y libusb-1.0.0 libudev-dev
      - name: Install node
        uses: actions/setup-node@v3
      - name: Install yarn
        run: |
          npm install -g yarn
      - name: Build Ledger app
        run: make
      - name: Build/Install build js deps
        run: make zemu_install
      - name: Run zemu tests
        run: "cd tests_zemu; yarn test"
      - name: Upload Snapshots (only failure)
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: snapshots-tmp
          path: tests_zemu/snapshots-tmp/

  build_package_nanos:
    needs: [configure, build, build_ledger, test_zemu]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    container:
      image: zondax/ledger-app-builder:latest
      options: --user ${{ needs.configure.outputs.uid_gid }}
      env:
        BOLOS_SDK: /opt/nanos-secure-sdk
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install deps
        run: pip install --break-system-packages ledgerblue

      - name: Build NanoS
        shell: bash -l {0}
        run: |
          make
          mv ./app/pkg/installer_s.sh ./app/pkg/installer_nanos.sh
     
  build_package_nanosp:
    needs: [configure, build, build_ledger, test_zemu]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    container:
      image: zondax/ledger-app-builder:latest
      options: --user ${{ needs.configure.outputs.uid_gid }}
      env:
        BOLOS_SDK: /opt/nanosplus-secure-sdk
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install deps
        run: pip install --break-system-packages ledgerblue

      - name: Build NanoSP
        shell: bash -l {0}
        run: |
          make
          mv ./app/pkg/installer_s2.sh ./app/pkg/installer_nanos_plus.sh
  
  build_package_nanox:
    needs: [configure, build, build_ledger, test_zemu]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    container:
      image: zondax/ledger-app-builder:latest
      options: --user ${{ needs.configure.outputs.uid_gid }}
      env:
        BOLOS_SDK: /opt/nanox-secure-sdk
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install deps
        run: pip install --break-system-packages ledgerblue

      - name: Build NanoX
        shell: bash -l {0}
        run: |
          make
          mv ./app/pkg/installer_x.sh ./app/pkg/installer_nanox.sh

  build_package_stax:
    needs: [configure, build, build_ledger, test_zemu]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    container:
      image: zondax/ledger-app-builder:latest
      options: --user ${{ needs.configure.outputs.uid_gid }}
      env:
        BOLOS_SDK: /opt/stax-secure-sdk
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install deps
        run: pip install --break-system-packages ledgerblue

      - name: Build Stax
        shell: bash -l {0}
        run: |
          PRODUCTION_BUILD=0 make
     
  build_package_flex:
    needs: [configure, build, build_ledger, test_zemu]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    container:
      image: zondax/ledger-app-builder:latest
      options: --user ${{ needs.configure.outputs.uid_gid }}
      env:
        BOLOS_SDK: /opt/flex-secure-sdk
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install deps
        run: pip install --break-system-packages ledgerblue

      - name: Build Flex
        shell: bash -l {0}
        run: |
          PRODUCTION_BUILD=0 make